### ISSUE TITLE
checkstyletester: Yaml firmat for project list 

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#866]
We have now very weird format of project list.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties
It was quick and old decision.
Let's do yaml format for it.

**Comment by nrmancuso** [comment]
@romani please share an example of the format of this yaml

**Comment by relentless-pursuit** [comment]
Also, will the extenion change?

**Comment by rnveach** [comment]
I detailed the impact of this kind of change at https://github.com/checkstyle/contribution/pull/867#issuecomment-2133719970 and https://github.com/checkstyle/contribution/pull/867#issuecomment-2133724713. This type of change will be slightly mildly involved.

**Comment by nrmancuso** [comment]
Yeah, the issue description really doesn’t capture the large amount of work that will need to be done to support this.

**Comment by romani** [comment]
@nrmancuso , @rnveach , I updated description with more details.

**Comment by nrmancuso** [comment]
@romani please show the full document format in valid yaml. Also, we should use yaml/yml file extension

**Comment by romani** [comment]
I placed missed ":" now yaml is valid.

**Comment by nrmancuso** [comment]
IMO, project properties should not be array elements.

**Comment by rnveach** [comment]
Implementation specifics is still being discussed.

**Comment by romani** [comment]
>project properties should not be array elements

Please share snippet of config that you have in your mind

**Comment by nrmancuso** [comment]
yaml structure should be:

```yaml
projects:
  - checkstyle:
    scm: git
    url: https://github.com/checkstyle/checkstyle.git
    branch: master
    enabled: true
    excludes:
      - **/.ci-temp/**/*
      - **/resources-noncompilable/**/asttreestringprinter/**/*
      - **/resources-noncompilable/**/filefilters/**/*
  ...
```

Override can be provided by:
```bash
  groovy ./diff.groovy --listOfProjects projects-to-test-on.yaml  \
      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
      --useShallowClone \
      --allowExcludes --mode single -xm "-Dcheckstyle.failsOnError=false" \
      --projects.checkstyle.enabled=false
```
